version: '3'

services:
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
  postgres:
    image: postgres
    environment:
      - POSTGRES_PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=artemir
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  mail:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  postgres:
  redis:
