version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bookmarks
      - POSTGRES_USER=bookmarks
      - POSTGRES_PASSWORD=bookmarks

  redis:
    image: redis

  bookmarks:
    image: hub.starlab.md/afterwork/bookmarks:latest
    environment:
      - NGINX_PORT=80
      - NGINX_PROCESSES=2
      - DJANGO_EXECUTION_ENVIRONMENT=production
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_NAME=bookmarks
      - DJANGO_DATABASE_USER=bookmarks
      - DJANGO_DATABASE_PASSWORD=bookmarks
      - DJANGO_EMAIL_HOST_PASSWORD=yobobobo
      - DJANGO_EMAIL_HOST_USER=devs.after.work@gmail.com
      - CELERY_REDIS_DB=redis_db
      - CELERY_REDIS_HOST=redis
      - DJANGO_CELERY_BROKER_URL=redis://redis
      - DJANGO_CACHE_LOCATION=redis://redis:6379/1
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
